"""Modified Model Message

Revision ID: 30c38a226bd3
Revises: 59a01516a798
Create Date: 2024-03-18 09:47:23.342864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c38a226bd3'
down_revision = '59a01516a798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
